[ global ]
    output_path = "../../Outputs/DESForwardModel"

<include DESCovarianceMatrix.toml>

<include DESJacobian.toml>

[ sim ]
    num_sims = 2
    pippin_template = "PA_DESForwardModel.yml"

    [ sim.draw ] # Options for drawing from JLACovarianceMatrix
        SURVEY_LIST_SAMEMAGSYS = ["CFA3", "OTHER", "CALAN_TOLOLO"] 
        SURVEY_LIST_SAMEFILTER = ["CFA1", "CFA2", "CFA3", "CALAN_TOLOLO"]
        shift_map = {"CfA1" = "MAGSHIFT", "CfA2" = "MAGSHIFT"}

    [ sim.priors ]
        Om.distribution = "Uniform"
        Om.args = [0, 1]
        Om.init = 0.3

        w0.distribution = "Normal"
        w0.args = [-1.0, 1.0]
        w0.init = -1.0
