[ global ]
    output_path = "../../Outputs/DESForwardModel"

<include DESCovarianceMatrix.toml>

<include DESJacobian.toml>

[ sim ]
    simulate = 1
    pippin_template = "PA_DESForwardModel.yml"
    [ sim.config.priors ]
        Om.distribution = "Uniform"
        Om.args = [0, 1]
        Om.init = 0.3

        w0.distribution = "Normal"
        w0.args = [-1.0, 1.0]
        w0.init = -1.0
